version: '2'
services:
        edgeimpulse-inference:
                build: ./edgeimpulse-inference
                restart: always 
        balena-cam:
                build: ./balena-cam
                privileged: true
                restart: always
                depends_on:
                        - edgeimpulse-inference
                ports:
                        - "80"
                labels:
                        io.balena.features.kernel-modules: '1'
        coturn:
                restart: unless-stopped
                build: ./coturn-docker-image
                ports:
                        - "3478:3478/udp"
                        - "49200-49400:49200-49400/udp"
