version: '2'
services:
        balena-cam:
                build: ./balena-cam
                privileged: true
                restart: always
                ports:
                        - "80:80"
