version: '2'
services:
        edgeimpulse-inference:
                build: ./edgeimpulse-inference
                restart: always
        balena-cam:
                build: ./balena-cam
                privileged: true
                restart: always
                depends_on:
                        - edgeimpulse-inference
                ports:
                        - "32343:80"
                labels:
                        io.balena.features.kernel-modules: '1'
                volumes:
                        - ./balena-cam/app:/usr/src/app
